#!/usr/bin/env bash
# Script that it configures a brand new Ubuntu machine to the requirements asked

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo service nginx restart
