#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 29939-web-01 44.210.84.85 check port 80
        server 29939-web-02 18.234.193.81 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
