#!/usr/bin/env bash
#Program that prints FizzBuzz sequence
var=1
while [ $var -ne 101 ]
do
	if [ $(( var % 15 )) -eq 0 ]
	then
		echo "FizzBuzz"
	
	elif [ 	$(( var % 5 )) -eq 0 ]
	then
		echo "Buzz"
	
	elif [ $(( var % 3 )) -eq 0 ]
	then
		echo "Fizz"

	else
		echo $var
	fi
	var=$(( var + 1 ))
done
